//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 03/17/2020 15:00:06 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace Retail.DAL.Models
{
	/// <summary>
	/// 
	/// </summary>
	public class retail_order
	{

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
		public System.Int64  Id { get; set;}
		/// <summary>
		/// 订单号
		/// </summary>
		public System.String  OrderNum { get; set;}
		/// <summary>
		/// 订单日期
		/// </summary>
		public System.DateTime  OrderDate { get; set;}
		/// <summary>
		/// 客户id
		/// </summary>
		public System.Int32  CustomId { get; set;}=0;
		/// <summary>
		/// 客户名称
		/// </summary>
		public System.String  CustomName { get; set;}
		/// <summary>
		/// 联系人
		/// </summary>
		public System.String  Relation { get; set;}=string.Empty;
		/// <summary>
		/// 联系方式
		/// </summary>
		public System.String  RelationPhone { get; set;}=string.Empty;
		/// <summary>
		/// 详细地址
		/// </summary>
		public System.String  Address { get; set;}=string.Empty;
		/// <summary>
		/// 付款方式 1：款到发货 2：货到付款 3：已付 4：部分付款
		/// </summary>
		public System.Int32  PayMentType { get; set;}=0;
		/// <summary>
		/// 订单原价
		/// </summary>
		public System.Decimal  OriginalPrice { get; set;}
		/// <summary>
		/// 订单折扣
		/// </summary>
		public System.Decimal  OrderDiscount { get; set;}
		/// <summary>
		/// 订单折扣金额
		/// </summary>
		public System.Decimal  OrderDiscountAmount { get; set;}
		/// <summary>
		/// 
		/// </summary>
		public System.Decimal  ReceivePrice { get; set;}
		/// <summary>
		/// 支付状态 1：已支付 0：未支付
		/// </summary>
		public System.Int32  PayStatus { get; set;}=0;
		/// <summary>
		/// 支付时间
		/// </summary>
		public System.DateTime  PayDate { get; set;}=new DateTime();
		/// <summary>
		/// 订单状态
		/// </summary>
		public System.Int32  OrderStatus { get; set;}=0;
		/// <summary>
		/// 来源
		/// </summary>
		public System.Int32  Source { get; set;}=0;
		/// <summary>
		/// 备注
		/// </summary>
		public System.String  Remark { get; set;}=string.Empty;
		/// <summary>
		/// 企业Id
		/// </summary>
		public System.Int32  CompanyId { get; set;}=0;
		/// <summary>
		/// 集团Id
		/// </summary>
		public System.Int32  CompanyPid { get; set;}=0;
		/// <summary>
		/// 机器id
		/// </summary>
		public System.Int32  MachineId { get; set;}=0;
		/// <summary>
		/// 员工Id
		/// </summary>
		public System.Int32  UserId { get; set;}=0;
		/// <summary>
		/// 销售员
		/// </summary>
		public System.String  SaleMan { get; set;}=string.Empty;
		/// <summary>
		/// 上传时间
		/// </summary>
		public System.DateTime  CreateTime { get; set;}=new DateTime();
	}
}

                