//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 03/17/2020 15:00:06 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace Retail.DAL.Models
{
	/// <summary>
	/// 
	/// </summary>
	public class retail_order_item
	{

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
		public System.Int64  Id { get; set;}
		/// <summary>
		/// 订单号
		/// </summary>
		public System.String  OrderNum { get; set;}
		/// <summary>
		/// 订单日期
		/// </summary>
		public System.DateTime  OrderDate { get; set;}=new DateTime();
		/// <summary>
		/// 产品Id
		/// </summary>
		public System.Int64  ProductId { get; set;}
		/// <summary>
		/// 产品名称
		/// </summary>
		public System.String  ProductName { get; set;}=string.Empty;
		/// <summary>
		/// 顺序号
		/// </summary>
		public System.Int32  SordIndex { get; set;}=0;
		/// <summary>
		/// 产品标准单位
		/// </summary>
		public System.String  ProductUnitName { get; set;}=string.Empty;
		/// <summary>
		/// 规格Id
		/// </summary>
		public System.Int64  SizeId { get; set;}=0;
		/// <summary>
		/// 规格名称
		/// </summary>
		public System.String  SizeName { get; set;}=string.Empty;
		/// <summary>
		/// 是否是单规格产品
		/// </summary>
		public System.Int32  IsSingleSize { get; set;}=0;
		/// <summary>
		/// 原价
		/// </summary>
		public System.Decimal  OriginalPrice { get; set;}
		/// <summary>
		/// 单品折扣
		/// </summary>
		public System.Decimal  ItemDiscount { get; set;}
		/// <summary>
		/// 折扣优惠
		/// </summary>
		public System.Decimal  ItemDiscountPrice { get; set;}
		/// <summary>
		/// 其他优惠
		/// </summary>
		public System.Decimal  PromotionPrice { get; set;}
		/// <summary>
		/// 现价
		/// </summary>
		public System.Decimal  BuyPrice { get; set;}
		/// <summary>
		/// 订购数量
		/// </summary>
		public System.Decimal  BuyCount { get; set;}
		/// <summary>
		/// 打包单位
		/// </summary>
		public System.String  PackUnitName { get; set;}=string.Empty;
		/// <summary>
		/// 换算倍数
		/// </summary>
		public System.Decimal  ConversionValue { get; set;}
		/// <summary>
		/// 产品描述
		/// </summary>
		public System.String  ProductDescription { get; set;}=string.Empty;
		/// <summary>
		/// Guid
		/// </summary>
		public System.String  ItemGuid { get; set;}=string.Empty;
		/// <summary>
		/// 备注
		/// </summary>
		public System.String  Remark { get; set;}=string.Empty;
		/// <summary>
		/// 企业Id
		/// </summary>
		public System.Int32  CompanyId { get; set;}=0;
		/// <summary>
		/// 集团Id
		/// </summary>
		public System.Int32  CompanyPid { get; set;}=0;
		/// <summary>
		/// 机器Id
		/// </summary>
		public System.Int32  MachineId { get; set;}=0;
		/// <summary>
		/// 创建日期
		/// </summary>
		public System.DateTime  CreateDate { get; set;}=new DateTime();
	}
}

                