//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 03/05/2020 16:15:34 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace Retail.DAL.Models
{
	/// <summary>
	/// 
	/// </summary>
	public class retail_province
	{

		/// <summary>
		/// 
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
		public System.Int32  Id { get; set;}
		/// <summary>
		/// 
		/// </summary>
		public System.Int32  ProvinceId { get; set;}
		/// <summary>
		/// 
		/// </summary>
		public System.String  Name { get; set;}
	}
}

                