//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 03/06/2020 14:21:40 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace Retail.DAL.Models
{
	/// <summary>
	/// 
	/// </summary>
	public class retail_product
	{

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
		public System.Int64  Id { get; set;}
		/// <summary>
		/// 产品编码
		/// </summary>
		public System.String  ProductCode { get; set;}=string.Empty;
		/// <summary>
		/// 产品名称
		/// </summary>
		public System.String  ProductName { get; set;}
		/// <summary>
		/// 单位
		/// </summary>
		public System.Int32  UnitId { get; set;}
		/// <summary>
		/// 产品描述
		/// </summary>
		public System.String  Description { get; set;}=string.Empty;
		/// <summary>
		/// 分类Id
		/// </summary>
		public System.Int32  CategoryId { get; set;}=0;
		/// <summary>
		/// 
		/// </summary>
		public System.Int32  SordIndex { get; set;}=0;
		/// <summary>
		/// 图片地址
		/// </summary>
		public System.String  ImgUrl { get; set;}=string.Empty;
		/// <summary>
		/// 是否是单规格产品，1：是 0：否
		/// </summary>
		public System.Int32  IsSingleSize { get; set;}=0;
		/// <summary>
		/// 搜索码
		/// </summary>
		public System.String  SearchCode { get; set;}=string.Empty;
		/// <summary>
		/// 是否可用 1：可用 0：停用
		/// </summary>
		public System.Int32  Status { get; set;}=0;
		/// <summary>
		/// 所属企业
		/// </summary>
		public System.Int32  CompanyPid { get; set;}
		/// <summary>
		/// 创建时间
		/// </summary>
		public System.DateTime  CreateDate { get; set;}=new DateTime();
	}
}

                