//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 03/06/2020 14:21:40 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace Retail.DAL.Models
{
	/// <summary>
	/// 企业员工信息表
	/// </summary>
	public class retail_user
	{

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
		public System.Int32  Id { get; set;}
		/// <summary>
		/// 姓名
		/// </summary>
		public System.String  UserName { get; set;}
		/// <summary>
		/// 登录账号
		/// </summary>
		public System.String  LoginName { get; set;}
		/// <summary>
		/// 登录密码
		/// </summary>
		public System.String  LoginPwd { get; set;}
		/// <summary>
		/// 性别，0：男 1：女
		/// </summary>
		public System.Int32  Sex { get; set;}
		/// <summary>
		/// 出生日期
		/// </summary>
		public System.DateTime  Birthday { get; set;}=new DateTime();
		/// <summary>
		/// 联系方式
		/// </summary>
		public System.String  Telephone { get; set;}=string.Empty;
		/// <summary>
		/// 联系地址
		/// </summary>
		public System.String  Address { get; set;}=string.Empty;
		/// <summary>
		/// 所属企业
		/// </summary>
		public System.Int32  CompanyId { get; set;}
		/// <summary>
		/// 创建日期
		/// </summary>
		public System.DateTime  CreateDate { get; set;}
		/// <summary>
		/// 创建日期
		/// </summary>
		public System.DateTime  ModifyDate { get; set;}
		/// <summary>
		/// 备注
		/// </summary>
		public System.String  Remark { get; set;}=string.Empty;
	}
}

                