//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 03/17/2020 15:00:06 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace Retail.DAL.Models
{
	/// <summary>
	/// 
	/// </summary>
	public class retail_category
	{

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
		public System.Int32  Id { get; set;}
		/// <summary>
		/// 分类编码
		/// </summary>
		public System.String  CategoryCode { get; set;}=string.Empty;
		/// <summary>
		/// 分类名称
		/// </summary>
		public System.String  CategoryName { get; set;}
		/// <summary>
		/// 顺序码
		/// </summary>
		public System.Int32  SordIndex { get; set;}=0;
		/// <summary>
		/// 分类类别，1：一级分类 2:二级分类
		/// </summary>
		public System.Int32  CategoryType { get; set;}
		/// <summary>
		/// 上一级分类Id
		/// </summary>
		public System.Int32  ParentId { get; set;}=0;
		/// <summary>
		/// 所属企业
		/// </summary>
		public System.Int32  CompanyPid { get; set;}=0;
		/// <summary>
		/// 是否可用 1：可用 0：不可用
		/// </summary>
		public System.Int32  Status { get; set;}=0;
	}
}

                