//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 03/06/2020 14:21:39 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace Retail.DAL.Models
{
	/// <summary>
	/// 城市信息表
	/// </summary>
	public class retail_city
	{

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
		public System.Int32  Id { get; set;}
		/// <summary>
		/// 城市编码
		/// </summary>
		public System.Int32  CityId { get; set;}
		/// <summary>
		/// 城市名称
		/// </summary>
		public System.String  Name { get; set;}
		/// <summary>
		/// 所属省份编码
		/// </summary>
		public System.Int32  ProvinceId { get; set;}
	}
}

                