//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 03/05/2020 16:15:34 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace Retail.DAL.Models
{
	/// <summary>
	/// 
	/// </summary>
	public class retail_product_size
	{

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true)]
		public System.Int64  Id { get; set;}
		/// <summary>
		/// 产品Id
		/// </summary>
		public System.Int64  ProductId { get; set;}
		/// <summary>
		/// 规格Id
		/// </summary>
		public System.Int32  SizeId { get; set;}
		/// <summary>
		/// 规格名称
		/// </summary>
		public System.String  SizeName { get; set;}
		/// <summary>
		/// 单位Id
		/// </summary>
		public System.Int32  UnitId { get; set;}
		/// <summary>
		/// 单位名称
		/// </summary>
		public System.String  UnitName { get; set;}=string.Empty;
		/// <summary>
		/// 单价
		/// </summary>
		public System.Decimal  Price { get; set;}
		/// <summary>
		/// 描述
		/// </summary>
		public System.String  Description { get; set;}=string.Empty;
		/// <summary>
		/// 换算值，倍数关系
		/// </summary>
		public System.Decimal  ConversionValue { get; set;}
		/// <summary>
		/// 采购单价
		/// </summary>
		public System.Decimal  PurchasePrice { get; set;}
		/// <summary>
		/// 采购单位
		/// </summary>
		public System.Int32  PurchaseUnitId { get; set;}=0;
		/// <summary>
		/// 采购单位
		/// </summary>
		public System.String  PurchaseUnitName { get; set;}=string.Empty;
		/// <summary>
		/// 采购换算倍数
		/// </summary>
		public System.Decimal  PurchaseConversionValue { get; set;}
	}
}

                