//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 03/06/2020 14:21:40 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace Retail.DAL.Models
{
	/// <summary>
	/// 
	/// </summary>
	public class retail_ref_company_category
	{

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
		public System.Int64  Id { get; set;}
		/// <summary>
		/// 分类Id
		/// </summary>
		public System.Int32  CategoryId { get; set;}
		/// <summary>
		/// 所属企业
		/// </summary>
		public System.Int32  CompanyId { get; set;}
		/// <summary>
		/// 所属企业父Id
		/// </summary>
		public System.Int32  CompanyPid { get; set;}
	}
}

                