//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 03/17/2020 15:00:06 By DESKTOP-6T15791
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SqlSugar;

namespace Retail.DAL.Models
{
	/// <summary>
	/// 
	/// </summary>
	public class retail_machine
	{

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
		public System.Int32  Id { get; set;}
		/// <summary>
		/// 
		/// </summary>
		public System.String  MachineName { get; set;}
		/// <summary>
		/// 机器类型
		/// </summary>
		public System.Int32  MachineType { get; set;}
		/// <summary>
		/// 企业Id
		/// </summary>
		public System.Int32  CompanyId { get; set;}
		/// <summary>
		/// 是否可用，1：可用 0：停用
		/// </summary>
		public System.Int32  Status { get; set;}
		/// <summary>
		/// 
		/// </summary>
		public System.DateTime  CreateTime { get; set;}=new DateTime();
		/// <summary>
		/// 绑定Uid
		/// </summary>
		public System.String  BindUid { get; set;}=string.Empty;
		/// <summary>
		/// 绑定的电脑名称
		/// </summary>
		public System.String  BindComputerName { get; set;}=string.Empty;
	}
}

                